In [56]:
import numpy as np
import array

In [137]:
#additon of two matrix using numpy
def array(arr1,arr2):
    arr1=np.array([3,2,1])
    arr2=np.array([1,0,0])
    add_matrix=np.add(arr1,arr2)
    return(add_matrix)
 
array(arr1,arr2)   

array([4, 2, 1])

In [440]:
#addition of two matrix 
class add_matrix():
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
        m1_row=len(self.m1)
        m2_row=len(self.m2)
        m1_col=len(self.m1[0])
        m2_col=len(self.m2[0])
        if((m1_row==m2_row)and(m1_col==m2_col)):
            print("you may proceed the addition matrix")
        else:
            print("OOPS!,its not same")
    try:          
        def add(self):
            for i in range(len(self.m1)):
                for j in range(len(self.m1[0])):
                    result[i][j]=m1[i][j]+m2[i][j]
            print(result)
    
    except Exception as e:
        print(e)
    
m1=[[1,2,3],[2,3,4]]
m2=[[1,1,1],[10,10,10]]          
result=[[0,0,0],[0,0,0]] 

m=add_matrix(m1,m2)
m.add()

you may proceed the addition matrix
[[2, 3, 4], [12, 13, 14]]


In [17]:
#mutiply the two matrix array
def multi_matrix(a,b,multi):

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                multi[i][j]+=a[i][k]*b[k][j]

    print(multi)

a=[[0,0,3],[7,1,6],[4,8,2]]
b=[[7,1,1,3],[0,7,8,0],[1,3,7,4]]
multi=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]


multi_matrix(a,b,multi)

[[3, 9, 21, 12], [55, 32, 57, 45], [30, 66, 82, 20]]


In [35]:
#multiplication of two array using numpy
import numpy as np
def multi(m1,m2,multi_array):
    m1=np.array([[2,-7,1],[5,3,7]])
    m2=np.array([[3,-2,1],[4,9,0]])
    multi_array=np.multiply(m1,m2)
    print("matrix of two array", multi_array)
    
multi(m1,m2,multi_array)

matrix of two array [[ 6 14  1]
 [20 27  0]]


In [46]:
#Transpose of matrix array using oops
class transpose():
    def __init__(self,arr):
        self.arr=arr
        print("The given matrix is ",arr)
    def __add__(self,other):
        for i in range(len(self.arr)):
            for j in range(len(self.arr[0])):
                result[j][i]=arr[i][j]
                
        print("the transpose of matrix is",result)        
            

arr=[[1,7],[4,5],[7,8]]
result=[[0,0,0],[0,0,0]]        

z=transpose(arr) 
z.__add__(result)

The given matrix is  [[1, 7], [4, 5], [7, 8]]
the transpose of matrix is [[1, 4, 7], [7, 5, 8]]


In [69]:
#Transpose of matrix array using 
def tranx_matrix(ax):
    ax=np.array([[1,7],[4,5],[7,8]])
    tranx=np.transpose(ax)
    print("The transpose matrix of ax is",tranx)

tranx_matrix(ax)

the transpose matrix of ax is [[1 4 7]
 [7 5 8]]


In [98]:
#Program to Sort Words in Alphabetic Order
class sentence_sort():
    def __init__(self,sentence):
        self.sentence=sentence
        
    def __repr__(self):
        word=(self.sentence).split()
        word.sort()
        for words in word:
            print(words)
            
sentence="A journey of thousand miles begins with a single step"

alpha=sentence_sort(sentence)
alpha.__repr__()

A
a
begins
journey
miles
of
single
step
thousand
with


In [89]:
#remove punctuation mark in given string
def punc_mark(word):
    punc=[".",",","!",":","`","''",";","~",",","?"]
    word="Maya: why do not they know who is responsible?,they asked."
    print("The string is:",word)
    for i in word:
        if i in punc:
            word=word.replace(i," ")
         
    print("The remove punctuation in given string is:",word)
    
punc_mark(word)

The string is: Maya: why do not they know who is responsible?,they asked.
The remove punctuation in given string is: Maya  why do not they know who is responsible  they asked 
